file_format: "1"
id: kurnikas-split-lp
name: Kurnikas Split LP
type: shield
url: https://github.com/clegganator259/kurnikas-split-lp/
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - encoder
siblings:
  - kurnikas-split-lp-left
  - kurnikas-split-lp-right

